spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: categoryservice
        uri: lb://categoryservice
        predicates:
        - Path=/categories/**
        filters:
        - RewritePath=/categories/(?<path>.*), /$\{path}
  application:
    name: gateway-service
server:
  port: 8085




