
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: category-service
        uri: http://192.168.0.123:8769
        # uri: lb://category-service
        # uri: localhost:
        predicates:
        - Path=/categories/**
        filters:
        - RewritePath=/categories/(?<path>.*), /$\{path}
  application:
    name: gateway-service
server:
  port: 8085




