server:
  port: 8765
zuul:
  routes:
    categories:
      path: /categories/**
      serviceId: category-service
eureka:
  client:
    service-url:
      defaultZone: http://naming:8761/eureka/
    registerWithEureka: false
    fetchRegistry: true

spring:
  application:
    name: zuul-gateway


logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG